### ISSUE TITLE
HostedFiles filter is unknown

### ISSUE THREAD

**Issue by troysellers** [sinch/readme-sync#23]
When adding the Hosted Files filter to the config.yml, then pushing a category with changes. 

```
Unknown filter [0] specified in config file.
```

config.yml
```
categories:
  - overview

filters:
  - hostedFiles: 
    baseUrl: https://troysellers.github.io/docimages/
```
